CREATE DATABASE IF NOT EXISTS study_site CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE study_site;

CREATE TABLE IF NOT EXISTS consultations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(60) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  goal VARCHAR(255) NOT NULL,
  available_time VARCHAR(40) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
